server:
  port: 8085

spring:
  main:
    web-application-type: reactive
  webflux:
    problem details:
      enabled: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/users_db}
      auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:true}

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 600000

